### ISSUE TITLE
where do I find OCPNsenc to integrate it in a Linux package ?

### ISSUE THREAD

**Issue by dominig** [bdbcat/s63_pi#12]
When building the s63 plugin under Linux the build process should create a directory buildlinux64/OCPNsenc/OCPNsenc (64bits) or buildlinux/OCPNsenc/OCPNsenc (32 bits).
None of them are created.
There is no obvious rules , nor source for building them.

Result is an error at plugin installation.

Can we built OCPNsenc in the open ?
Where do we get the source ?

If not where do I find a staticaly built Lib that would work independently of the distro release?

**Comment by bdbcat** [comment]
dominig...

The OCPNsenc binaries are in the s63_pi github tree as prebuilt binaries. They are closed source due to S63 licensing requirements.

Are they not visible to you?

Maybe they need to be manually copied to the build target directory.  If so, this is indeed a bug in the CMake build rules.

Dave

Dave

**Comment by dominig** [comment]
Thanks.
I did a cleanup of my project and a new git clone and they are now there.
